### ISSUE TITLE
Server App

### ISSUE THREAD

**Issue by johndodev** [kublet/community#2]
Hello,

I'm a web developer, not a C++ developer, so I can't create apps.

However, I have seen and tried the server app that exposes an HTTP endpoint. The idea is nice, it works, and it is usable, it’s a good start.

I have some improvements suggestions for the C++ developers here, such as:

- A great feature would be to allow sending HTML and rendering it on the screen.
- or the ability to upload a picture or a GIF.
- Instead of listening locally, it would be better to send an HTTP endpoint, and the kubelet will query it regularly to update the display (the reccurence could be a setting, in second).
- Maybe include more parameters for colors, sizes, etc., and perhaps use JSON POST instead of query strings?

It would also be great to have minimal documentation available again on the phone app: just display the endpoint again when we click on "Server" in the app list if the server is already the installed app.

I don't see the server app in this repository, will it be included someday?

Thanks

**Comment by audreylim** [comment]
Hi John, thanks for your suggestions.

- We cannot display HTML on the screen, but we do have our [kgfx](https://developers.thekublet.com/docs/display/api/) library for quick and easy UI rendering. This library provides basic endpoints such as drawing text, numbers, and chart, with the ability to set size and colors, and should be sufficient for most use cases.
- We are working on the ability to upload a picture or GIF so do lookout for these updates on our [Instagram](https://www.instagram.com/thekublet/), Kickstarter page, or our mobile app.
- This would mean turning the kublet from a server to a client, so yes, we also have this planned.
- That's a good suggestion. We will add params for colors and sizes and maybe JSON POST.

The endpoint on the server app is dynamic, so it is better to let kublet display the endpoint. 

We aim to provide more examples in our community repo and may include the server example in future.

The examples in this repo are meant for beginners (in C++) to get started writing an app quickly. So even without C++ experience we encourage our users to start with the basic examples here and refer to our [documentation](https://developers.thekublet.com/docs/display/api/). We will publish more examples.

Thanks for your feedback and we looking forward to seeing your app!

**Comment by johndodev** [comment]
Ah ok, thanks !
